name: $(Rev:r)
jobs:
- job: Windows
  pool:
    vmImage: 'windows-latest'
  steps:
  # for this repo, `dotnet test` implies pack as it validates the .nupkg file
  - script: dotnet test --project tests/Equinox.Templates.Tests --report-xunit-trx --timeout 3300s --xunit-diagnostics on
    displayName: dotnet pack + test
    env:
      BUILD_ID: $(BUILD.BUILDNUMBER)
      CI: true
      BUILD_PR: $(SYSTEM.PULLREQUEST.PULLREQUESTNUMBER)
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'VSTest'
      testResultsFiles: 'tests/**/*.trx'
    condition: succeededOrFailed()
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: 'bin/nupkg'
      artifactName: 'nupkg'