name: $(Rev:r)
jobs:
- job: Windows
  pool:
    vmImage: 'windows-latest'
  variables:
    BUILD_ID: $(BUILD.BUILDNUMBER)
    BUILD_PR: $(SYSTEM.PULLREQUEST.PULLREQUESTNUMBER)
    CI: true
  steps:
  # for this repo, `dotnet test` requires a build/pack as it validates the .nupkg file
  - script: dotnet pack src/Equinox.Templates
    displayName: dotnet pack
  - script: dotnet test --project tests/Equinox.Templates.Tests --report-xunit-trx --timeout 3300s --xunit-diagnostics on
    displayName: dotnet test
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'VSTest'
      testResultsFiles: 'tests/**/*.trx'
    condition: succeededOrFailed()
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: 'bin/nupkg'
      artifactName: 'nupkg'