{
 "title": "Equinox Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "sys",
    "label": "System",
    "query": {
     "query": "label_values({__name__=~\"(equinox|propulsion).*\"}, sys)"
    }
   },
   {
    "name": "sub",
    "label": "Sub-System",
    "query": {
     "query": "label_values({__name__=~\"(equinox|propulsion).*\", sys=~\"$sys\"}, sub)"
    }
   },
   {
    "name": "application",
    "label": "Application",
    "query": {
     "query": "label_values({__name__=~\"(equinox|propulsion).*\", sys=~\"$sys\", sub=~\"$sub\"}, app)"
    }
   },
   {
    "name": "database",
    "label": "Database",
    "query": {
     "query": "label_values({__name__=~\"(equinox|propulsion).*\", sys=~\"$sys\", sub=~\"$sub\"}, db)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values({__name__=~\"(equinox|propulsion).*\", sys=~\"$sys\", sub=~\"$sub\"}, con)"
    }
   },
   {
    "name": "category",
    "label": "Category",
    "query": {
     "query": "label_values({__name__=~\"(equinox|propulsion).*\", sys=~\"$sys\", sub=~\"$sub\"}, cat)"
    }
   },
   {
    "name": "facet",
    "label": "Facet",
    "query": {
     "query": "label_values({__name__=~\"(equinox|propulsion).*\", sys=~\"$sys\", sub=~\"$sub\"}, facet)"
    }
   },
   {
    "name": "operation",
    "label": "Operation",
    "query": {
     "query": "label_values({__name__=~\"(equinox|propulsion).*\", sys=~\"$sys\", sub=~\"$sub\"}, op)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Equinox Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Equinox Traffic",
     "type": "stat",
     "description": "Successful Transact / Query operations throughput",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 181 },
     "repeat": "application",
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (app)\n(rate(equinox_op_seconds_count{sys=~\"$sys\", sub=~\"$sub\", app=~\"$application\", db=~\"$database\", con=~\"$container\", cat=~\"$category\", facet=~\"$facet\", op=~\"$operation\"}[1m]))\n",
       "legendFormat": "{{app}}"
      }
     ]
    },
    {
     "title": "CosmosDB Consumption",
     "type": "stat",
     "description": "Amount of RU/s consumed by successful operations carried out via Equinox Transact or Query operations",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 181 },
     "repeat": "application",
     "fieldConfig": { "defaults": { "unit": "RU/s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (app)\n(rate(equinox_op_ru_sum{sys=~\"$sys\", sub=~\"$sub\", app=~\"$application\", db=~\"$database\", con=~\"$container\", cat=~\"$category\", facet=~\"$facet\", op=~\"$operation\"}[1m]))\n",
       "legendFormat": "{{app}}"
      }
     ]
    },
    {
     "title": "Latency p99/95/50",
     "type": "graph",
     "description": "Latency per Transact / Query operation (may involve >1 roundtrip in some cases)",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 187 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum by (app, facet, quantile)\n(equinox_op_summary_seconds{sys=~\"$sys\", sub=~\"$sub\", app=~\"$application\", db=~\"$database\", con=~\"$container\", facet=~\"$facet\"})"
      }
     ]
    },
    {
     "title": "CosmosDB Request Charges p99/95/50",
     "type": "graph",
     "description": "RU charges per Equinox internal operation (in some cases this may be the result of >1 roundtrip)",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 187 },
     "yaxes": [
      { "format": "short", "label": "RU/s" }
     ],
     "targets": [
      {
       "expr": "sum by (app, facet, quantile)\n(equinox_op_summary_ru{sys=~\"$sys\", sub=~\"$sub\", app=~\"$application\", db=~\"$database\", con=~\"$container\", facet=~\"$facet\"})"
      }
     ]
    },
    {
     "title": "Traffic (Equinox CosmosDb Operations)",
     "type": "graph",
     "description": "Equinox Operation counts, grouped by Facet and Category ",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 194 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum by (cat, facet)\n(rate(equinox_op_seconds_count{sys=~\"$sys\", sub=~\"$sub\", app=~\"$application\", db=~\"$database\", con=~\"$container\", cat=~\"$category\", facet=~\"$facet\", op=~\"$operation\"}[1m]))",
       "legendFormat": "{{cat}}: {{facet}}"
      }
     ]
    },
    {
     "title": "Saturation (Equinox CosmosDB Load)",
     "type": "graph",
     "description": "Equinox-incurred RU charges, grouped by Facet and Category ",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 194 },
     "yaxes": [
      { "format": "short", "label": "RU/s" }
     ],
     "targets": [
      {
       "expr": "sum by (cat, facet)\n(rate(equinox_op_ru_sum{sys=~\"$sys\", sub=~\"$sub\", app=~\"$application\", db=~\"$database\", con=~\"$container\", cat=~\"$category\", facet=~\"$facet\", op=~\"$operation\"}[1m]))",
       "legendFormat": "{{cat}}: {{facet}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Performance By Stream Category",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latency Distribution for $category",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
     "repeat": "category",
     "targets": [
      {
       "expr": "sum(rate(equinox_op_seconds_bucket{sys=~\"$sys\", sub=~\"$sub\", app=~\"$application\", db=~\"$database\", con=~\"$container\", cat=~\"$category\", facet=~\"$facet\", op=~\"$operation\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Request Charge Distribution for $category",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
     "repeat": "category",
     "targets": [
      {
       "expr": "sum(rate(equinox_op_ru_bucket{sys=~\"$sys\", sub=~\"$sub\", app=~\"$application\", cat=~\"$category\", facet=~\"$facet\", op=~\"$operation\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Performance By Facet (Query/Transact/Prune)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latency Distribution for $facet/$operation",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "repeat": "facet",
     "targets": [
      {
       "expr": "sum(rate(equinox_op_seconds_bucket{sys=~\"$sys\", sub=~\"$sub\", app=~\"$application\", db=~\"$database\", con=~\"$container\", cat=~\"$category\", facet=~\"$facet\", op=~\"$operation\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Request Charge Distribution for $facet/$operation",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "repeat": "facet",
     "targets": [
      {
       "expr": "sum(rate(equinox_op_ru_bucket{sys=~\"$sys\", sub=~\"$sub\", app=~\"$application\", cat=~\"$category\", facet=~\"$facet\", op=~\"$operation\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Performance for $application",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "repeat": "application",
   "collapsed": true,
   "panels": [
    {
     "title": "Latency Distribution for $application",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
     "targets": [
      {
       "expr": "sum(rate(equinox_op_seconds_bucket{sys=~\"$sys\", sub=~\"$sub\", app=~\"$application\", db=~\"$database\", con=~\"$container\", cat=~\"$category\", facet=~\"$facet\", op=~\"$operation\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Request Charge Distribution for $application",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
     "targets": [
      {
       "expr": "sum(rate(equinox_op_ru_bucket{sys=~\"$sys\", sub=~\"$sub\", app=~\"$application\", db=~\"$database\", con=~\"$container\", cat=~\"$category\", facet=~\"$facet\", op=~\"$operation\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Performance quantiles for $application",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "repeat": "application",
   "collapsed": true,
   "panels": [
    {
     "title": "Operation Latency Quantiles for $application",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 75 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum by (facet, quantile)\n(equinox_op_summary_seconds{sys=~\"$sys\", sub=~\"$sub\", app=~\"$application\", db=~\"$database\", con=~\"$container\", facet=~\"$facet\"})"
      }
     ]
    },
    {
     "title": "CosmosDB Request Charge quantiles for $application",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 75 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (facet, quantile)\n(equinox_op_summary_ru{sys=~\"$sys\", sub=~\"$sub\", app=~\"$application\", facet=~\"$facet\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Traffic for $application",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "repeat": "application",
   "collapsed": true,
   "panels": [
    {
     "title": "Traffic for $application",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 229 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (cat, op)\n(rate(equinox_op_seconds_count{sys=~\"$sys\", sub=~\"$sub\", app=~\"$application\", db=~\"$database\", con=~\"$container\", cat=~\"$category\", facet=~\"$facet\", op=~\"$operation\"}[1m])) ",
       "legendFormat": "{{cat}}: {{op}}"
      }
     ]
    },
    {
     "title": "CosmosDB Usage for $application",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 229 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (cat, facet)\n(rate(equinox_op_ru_sum{sys=~\"$sys\", sub=~\"$sub\", app=~\"$application\", db=~\"$database\", con=~\"$container\", cat=~\"$category\", facet=~\"$facet\", op=~\"$operation\"}[1m]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Payloads (bytes, events)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Event Payloads (count)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum by (facet, outcome)\n(rate(equinox_payload_events_total{sys=~\"$sys\", sub=~\"$sub\", app=~\"$application\", db=~\"$database\", con=~\"$container\", cat=~\"$category\", facet=~\"$facet\", op=~\"$operation\"}[1m]))"
      }
     ]
    },
    {
     "title": "Event Payloads (bytes)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum by (facet, outcome)\n(rate(equinox_payload_bytes_total{sys=~\"$sys\", sub=~\"$sub\", app=~\"$application\", db=~\"$database\", con=~\"$container\", cat=~\"$category\", facet=~\"$facet\", op=~\"$operation\"}[1m]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Payloads (bytes, events) for $application",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "repeat": "application",
   "collapsed": true,
   "panels": [
    {
     "title": "Event Payloads (count)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum by (cat, facet, op, outcome)\n(rate(equinox_payload_events_total{sys=~\"$sys\", sub=~\"$sub\", app=~\"$application\", db=~\"$database\", con=~\"$container\", cat=~\"$category\", facet=~\"$facet\", op=~\"$operation\"}[1m]))"
      }
     ]
    },
    {
     "title": "Event Payloads (bytes)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum by (cat, facet, op, outcome)\n(rate(equinox_payload_bytes_total{sys=~\"$sys\", sub=~\"$sub\", app=~\"$application\", db=~\"$database\", con=~\"$container\", cat=~\"$category\", facet=~\"$facet\", op=~\"$operation\"}[1m]))"
      }
     ]
    }
   ]
  }
 ]
}