{
 "title": "Propulsion Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "sys",
    "label": "System",
    "query": {
     "query": "label_values({__name__=~\"(equinox|propulsion).*\"}, sys)"
    }
   },
   {
    "name": "sub",
    "label": "Sub-System",
    "query": {
     "query": "label_values({__name__=~\"(equinox|propulsion).*\", sys=~\"$sys\"}, sub)"
    }
   },
   {
    "name": "application",
    "label": "Application",
    "query": {
     "query": "label_values({__name__=~\"(equinox|propulsion).*\", sys=~\"$sys\", sub=~\"$sub\"}, app)"
    }
   },
   {
    "name": "database",
    "label": "Database",
    "query": {
     "query": "label_values({__name__=~\"(equinox|propulsion).*\", sys=~\"$sys\", sub=~\"$sub\"}, db)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values({__name__=~\"(equinox|propulsion).*\", sys=~\"$sys\", sub=~\"$sub\"}, con)"
    }
   },
   {
    "name": "category",
    "label": "Category",
    "query": {
     "query": "label_values({__name__=~\"(equinox|propulsion).*\", sys=~\"$sys\", sub=~\"$sub\"}, cat)"
    }
   },
   {
    "name": "facet",
    "label": "Facet",
    "query": {
     "query": "label_values({__name__=~\"(equinox|propulsion).*\", sys=~\"$sys\", sub=~\"$sub\"}, facet)"
    }
   },
   {
    "name": "operation",
    "label": "Operation",
    "query": {
     "query": "label_values({__name__=~\"(equinox|propulsion).*\", sys=~\"$sys\", sub=~\"$sub\"}, op)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Propulsion Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Longest Running Stream Handler Duration",
     "type": "stat",
     "description": "Maximum duration a handler has been processing a stream",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by (app)\n(propulsion_scheduler_busy_seconds{kind=\"oldest\", state=\"active\", sys=~\"$sys\", sub=~\"$sub\", app=~\"$application\", db=~\"$database\"})",
       "legendFormat": "{{app}}"
      }
     ]
    },
    {
     "title": "Longest failing or stuck Stream Duration",
     "type": "stat",
     "description": "Longest durations a stream's handling has been stuck or failing",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by (app)\n(propulsion_scheduler_busy_seconds{kind=\"oldest\", state!=\"active\", sys=~\"$sys\", sub=~\"$sub\", app=~\"$application\", db=~\"$database\"})",
       "legendFormat": "{{app}}"
      }
     ]
    },
    {
     "title": "Handler Throughput (Successes)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by (app)\n(rate(propulsion_scheduler_handler_seconds_count{sys=~\"$sys\", sub=~\"$sub\", app=~\"$application\", kind!=\"exceptions\"}[5m]))",
       "legendFormat": "{{app}}"
      }
     ]
    },
    {
     "title": "Handler Throughput (Exceptions)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "max by (app)\n(rate(propulsion_scheduler_handler_seconds_count{sys=~\"$sys\", sub=~\"$sub\", app=~\"$application\", kind=\"exceptions\"}[5m]))",
       "legendFormat": "{{app}}"
      }
     ]
    },
    {
     "title": "Handler Latency (Successes p99)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "max by (app)\n(propulsion_scheduler_handler_summary_seconds{sys=~\"$sys\", sub=~\"$sub\", app=~\"$application\", kind!=\"exceptions\", quantile=\"0.99\"})",
       "legendFormat": "{{app}}"
      }
     ]
    },
    {
     "title": "Handler Latency (Exceptions p99)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "max by (app)\n(propulsion_scheduler_handler_summary_seconds{sys=~\"$sys\", sub=~\"$sub\", app=~\"$application\", kind=\"exceptions\", quantile=\"0.99\"})",
       "legendFormat": "{{app}}"
      }
     ]
    },
    {
     "title": "ChangeFeed Lag (Unprocessed Changed Documents Total)",
     "type": "stat",
     "description": "Unique changed documents awaiting processing\n\nNOTE net of read-ahead effects",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (app)\n(propulsion_changefeed_lag_documents{sys=~\"$sys\", sub=~\"$sub\", app=~\"$application\", db=~\"$database\"})",
       "legendFormat": "{{app}}"
      }
     ]
    },
    {
     "title": "CosmosDb ChangeFeed Age at Ingestion",
     "type": "stat",
     "description": "Age of most recently read batch\n\nNOTE due to read-ahead, age at the point of processing can be higher",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "dtdhms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by (app)\n(propulsion_changefeed_age_seconds{sys=~\"$sys\", sub=~\"$sub\", app=~\"$application\", db=~\"$database\"})",
       "legendFormat": "{{app}}"
      }
     ]
    },
    {
     "title": "Feed Read Offset",
     "type": "stat",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by (app, tranche)\n(propulsion_feed_position_token%1000000000)",
       "legendFormat": "{{app}} {{tranche}}"
      }
     ]
    },
    {
     "title": "Scheduler Buffered Streams (Queued + Active)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 24 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (app)\n(propulsion_scheduler_streams{sys=~\"$sys\", sub=~\"$sub\", app=~\"$application\", state!=\"synced\"})",
       "legendFormat": "{{app}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Propulsion Scheduler for $application",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "repeat": "application",
   "collapsed": true,
   "panels": [
    {
     "title": "Longest Stream Handler Busy State Durations",
     "type": "stat",
     "description": "Maximum duration a stream has been running, stuck or failing",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by (state)\n(propulsion_scheduler_busy_seconds{kind=\"oldest\", sys=~\"$sys\", sub=~\"$sub\", app=~\"$application\", db=~\"$database\"})",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "Handler Throughput (Successes)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(rate(propulsion_scheduler_handler_seconds_count{sys=~\"$sys\", sub=~\"$sub\", app=~\"$application\", kind!=\"exceptions\"}[5m]))"
      }
     ]
    },
    {
     "title": "Handler Throughput (Exceptions)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "max(rate(propulsion_scheduler_handler_seconds_count{sys=~\"$sys\", sub=~\"$sub\", app=~\"$application\", kind=\"exceptions\"}[5m]))"
      }
     ]
    },
    {
     "title": "Handler Latency (Successes)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "max by (quantile)\n(propulsion_scheduler_handler_summary_seconds{sys=~\"$sys\", sub=~\"$sub\", app=~\"$application\", kind!=\"exceptions\"})",
       "legendFormat": "Quantile {{quantile}}"
      }
     ]
    },
    {
     "title": "Handler Latency (Exceptions)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "max by (quantile)\n(propulsion_scheduler_handler_summary_seconds{sys=~\"$sys\", sub=~\"$sub\", app=~\"$application\", kind=\"exceptions\"})",
       "legendFormat": "Quantile {{quantile}}"
      }
     ]
    },
    {
     "title": "Handler Latency Distribution (Successes)",
     "type": "heatmap",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 67 },
     "targets": [
      {
       "expr": "sum(rate(propulsion_scheduler_handler_seconds_bucket{sys=~\"$sys\", sub=~\"$sub\", app=~\"$application\", kind!=\"exceptions\"}[5m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Handler Latency Distribution (Exceptions)",
     "type": "heatmap",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 67 },
     "targets": [
      {
       "expr": "sum(rate(propulsion_scheduler_handler_seconds_bucket{sys=~\"$sys\", sub=~\"$sub\", app=~\"$application\", kind=\"exceptions\"}[5m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Stream Handler Busy State Counts",
     "type": "timeseries",
     "description": "Number of streams with processing active, failing or stuck",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (state)\n(propulsion_scheduler_busy_count{sys=~\"$sys\", sub=~\"$sub\", app=~\"$application\", db=~\"$database\"})",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "Stream Handler Busy State Durations",
     "type": "timeseries",
     "description": "Breakdown of longest and shortest durations that streams have been active, stuck or stalled",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by (state, kind)\n(propulsion_scheduler_busy_seconds{sys=~\"$sys\", sub=~\"$sub\", app=~\"$application\", db=~\"$database\"})",
       "legendFormat": "{{state}} {{kind}} "
      }
     ]
    },
    {
     "title": "Propulsion Scheduler Buffers State (Total Events)",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 83 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(propulsion_scheduler_events{sys=~\"$sys\", sub=~\"$sub\", app=~\"$application\"})"
      }
     ]
    },
    {
     "title": "Propulsion Scheduler Buffers State (Total Payload Size)",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(propulsion_scheduler_bytes{sys=~\"$sys\", sub=~\"$sub\", app=~\"$application\"})"
      }
     ]
    },
    {
     "title": "Propulsion Scheduler Buffered (Streams)",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 88 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(propulsion_scheduler_streams{sys=~\"$sys\", sub=~\"$sub\", app=~\"$application\", state!=\"synced\"})"
      }
     ]
    },
    {
     "title": "Propulsion Scheduler Buffered (Categories)",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 93 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(propulsion_scheduler_cats{sys=~\"$sys\", sub=~\"$sub\", app=~\"$application\"})"
      }
     ]
    },
    {
     "title": "Propulsion Scheduler CPU Usage Breakdown",
     "type": "graph",
     "description": "Provides itemized breakdown of the work being performed by the (single) synchronous loop driving a Propulsion Scheduler",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum by (activity)\n(rate(propulsion_scheduler_cpu{sys=~\"$sys\", sub=~\"$sub\", app=~\"$application\"}[5m]))  ",
       "legendFormat": "{{activity}}"
      }
     ]
    },
    {
     "title": "Propulsion Scheduler Synced (Streams)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 103 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(propulsion_scheduler_streams{sys=~\"$sys\", sub=~\"$sub\", app=~\"$application\", state=\"synced\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Propulsion Feed overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Feed Read Rate (pages/s)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (app, tranche)\n(rate(propulsion_feed_pages_total{app=~\"$application\", db=~\"$database\"}[1m]))",
       "legendFormat": "{{app}} {{tranche}}"
      }
     ]
    },
    {
     "title": "Feed Read Rate (items/s)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (app, tranche)\n(rate(propulsion_feed_items_total{app=~\"$application\", db=~\"$database\"}[1m]))",
       "legendFormat": "{{app}} {{tranche}}"
      }
     ]
    },
    {
     "title": "Feed Baseline (Raw)",
     "type": "stat",
     "description": "Defines the baseline position from which the read begins. The meaning of the underlying value depends on the nature of the feed",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by (app, tranche)\n(propulsion_feed_position_token/1000000000)",
       "legendFormat": "{{app}} {{tranche}}"
      }
     ]
    },
    {
     "title": "Feed Read Offset",
     "type": "stat",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by (app, tranche)\n(propulsion_feed_position_token%1000000000)",
       "legendFormat": "{{app}} {{tranche}}"
      }
     ]
    },
    {
     "title": "Feed Read-ahead Buffer (Pages)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (app, tranche)\n(propulsion_feed_ingest_queue{sys=~\"$sys\", sub=~\"$sub\", app=~\"$application\", db=~\"$database\"})",
       "legendFormat": "{{app}} {{tranche}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CosmosDB Change Feed Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "ChangeFeed Read Rate (documents/s)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 87 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (app)\n(rate(propulsion_changefeed_documents_total{app=~\"$application\", db=~\"$database\"}[1m]))",
       "legendFormat": "{{app}}"
      }
     ]
    },
    {
     "title": "ChangeFeed Read Observed Age",
     "type": "stat",
     "description": "Age of most recently read batch\n\nNOTE due to read-ahead, age at the point of processing can be higher",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "dtdhms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by (app)\n(propulsion_changefeed_age_seconds{sys=~\"$sys\", sub=~\"$sub\", app=~\"$application\", db=~\"$database\"})",
       "legendFormat": "{{app}}"
      }
     ]
    },
    {
     "title": "ChangeFeed Lag (Unprocessed Changed Documents Total)",
     "type": "stat",
     "description": "Unique changed documents awaiting processing\n\nNOTE net of read-ahead effects",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (app)\n(propulsion_changefeed_lag_documents{sys=~\"$sys\", sub=~\"$sub\", app=~\"$application\", db=~\"$database\"})",
       "legendFormat": "{{app}}"
      }
     ]
    },
    {
     "title": "Read-ahead Buffer (Batches)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (app)\n(propulsion_changefeed_ingest_queue{sys=~\"$sys\", sub=~\"$sub\", app=~\"$application\", db=~\"$database\"})",
       "legendFormat": "{{app}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CosmosDB Change Feed Lag",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "ChangeFeed Read Observed Age",
     "type": "graph",
     "description": "Age of most recent documents read\nNote: due to read-ahead, age at the point of processing can be longer",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 179 },
     "yaxes": [
      { "format": "dtdhms" }
     ],
     "targets": [
      {
       "expr": "max by (app, rangeId)\n(propulsion_changefeed_age_seconds{sys=~\"$sys\", sub=~\"$sub\"})",
       "legendFormat": "{{app}}: Range {{rangeId}}"
      }
     ]
    },
    {
     "title": "ChangeFeed Lag (Unprocessed Changed Documents Total)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 188 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (app, rangeId)\n(propulsion_changefeed_lag_documents{sys=~\"$sys\", sub=~\"$sub\"})",
       "legendFormat": "{{app}}: Range {{rangeId}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CosmosDB Change Feed Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "ChangeFeed Read Rate (documents/s)",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (app, rangeId)\n(rate(propulsion_changefeed_documents_total{sys=~\"$sys\", sub=~\"$sub\"}[5m]))",
       "legendFormat": "{{app}}: Range {{rangeId}}"
      }
     ]
    },
    {
     "title": "ChangeFeed Read Charges (RU/s)",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (app)\n(rate(propulsion_changefeed_read_ru_sum{sys=~\"$sys\", sub=~\"$sub\"}[5m]))"
      }
     ]
    },
    {
     "title": "ChangeFeed Read Charge Distribution",
     "type": "heatmap",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 35 },
     "targets": [
      {
       "expr": "sum(rate(propulsion_changefeed_read_ru_bucket{sys=~\"$sys\", sub=~\"$sub\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "ChangeFeed Read Charges RU/s Total p99",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max by (app)\n(propulsion_changefeed_read_summary_ru{quantile=\"0.99\", sys=~\"$sys\", sub=~\"$sub\"})"
      }
     ]
    },
    {
     "title": "ChangeFeed Read Latency p99",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "propulsion_changefeed_read_summary_seconds{sys=~\"$sys\", sub=~\"$sub\", quantile=\"0.99\"}",
       "legendFormat": "{{app}}"
      }
     ]
    },
    {
     "title": "ChangeFeed Read Latency Distribution",
     "type": "heatmap",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 54 },
     "targets": [
      {
       "expr": "sum(rate(propulsion_changefeed_read_seconds_bucket{sys=~\"$sys\", sub=~\"$sub\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Read-ahead Pause Interval p99",
     "type": "graph",
     "description": "In a healthy system with consumers keeping up, pauses should be minimal (ingesting should take 0ms).\n\nIf the system is working down a backlog, the buffers being full triggers a pause at the point of ingestion until such time as there is space for another batch in the buffer, whereupon the reader is released to begin the next batch of documents",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "propulsion_changefeed_ingest_summary_seconds{quantile=\"0.99\", sys=~\"$sys\", sub=~\"$sub\"}",
       "legendFormat": "{{app}}"
      }
     ]
    },
    {
     "title": "Read-Ahead Pause Interval Distribution",
     "type": "heatmap",
     "description": "In a healthy system with consumers keeping up, pauses should be minimal.\n\nWhere the system is working down a backlog, pauses can occur (in fact the lack of them may suggest the read configuration can be enhanced)",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 66 },
     "targets": [
      {
       "expr": "sum(rate(propulsion_changefeed_ingest_seconds_bucket{sys=~\"$sys\", sub=~\"$sub\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  }
 ]
}