services:
  prometheus:
    build: ./prometheus
    ports:
      - "9090:9090"
    volumes:
        - type: bind
          source: ./config
          target: /var/lib/prometheus
          read_only: true
  grafana:
    build: ./grafana
    ports:
      - "3000:3000"
